"""Data access layer: load the CSV tables in data/ into plain dicts. Stdlib only.

The CSVs are generated by scripts/build.py from the evidence log (raw/listings_raw.tsv)
plus hand-curated tables, and checked by scripts/validate.py. Every other module reads
facts (dishes, ingredients, availability grades, listings, substitutions, utensils)
through this one file, so nothing else touches the filesystem. See docs/DATA_CARD.md
for what each table contains and how reliable it is.
"""
from __future__ import annotations

import csv
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def read_csv(name: str) -> list[dict]:
    with open(DATA / name, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


@lru_cache(maxsize=None)
def ingredients() -> dict[str, dict]:
    return {r["ingredient_id"]: r for r in read_csv("ingredients.csv")}


@lru_cache(maxsize=None)
def utensils() -> dict[str, dict]:
    return {r["utensil_id"]: r for r in read_csv("utensils.csv")}


@lru_cache(maxsize=None)
def dishes() -> dict[str, dict]:
    return {r["dish_id"]: r for r in read_csv("dishes.csv")}


@lru_cache(maxsize=None)
def dish_ingredients() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for r in read_csv("dish_ingredients.csv"):
        out.setdefault(r["dish_id"], []).append(r)
    return out


@lru_cache(maxsize=None)
def dish_utensils() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for r in read_csv("dish_utensils.csv"):
        out.setdefault(r["dish_id"], []).append(r)
    return out


def availability() -> dict[tuple[str, str], dict]:
    """(item_type, item_id) -> availability row. Requires build.py to have run."""
    return {(r["item_type"], r["item_id"]): r for r in read_csv("availability.csv")}


def listings() -> list[dict]:
    return read_csv("sg_listings.csv")
